main: penowl.plugin.migs.InvCtmr
name: MIGS
version: 1.8.3
author: PenguinOwl
description: An Ecomomy plugin that allows player to make easy shops from signs and chests
depends: [Vault]
website: https://dev.bukkit.org/projects/migs
commands:
  migs:
    description: The main MIGS command.
    usage: /<command> <reload|inspect|set> [value] [int|double|string]
    permission: migs.main
    permission-message: You don't have <permission>
permissions:
  migs.admin:
    description: Allows players to make admin shops.
  migs.main:
    description: Allows players to create and destroy shops.
    default: true
  migs.set:
    description: Allows players to manually edit config.
  migs.get:
    description: Allows players to manually inspect config.
  migs.*:
    description: Master permission for MIGS.
    children:
      - migs.admin
      - migs.main
      - migs.set
      - migs.inspect